version: "3"
services:
  frontend:
    build: .
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: yarn start-frontend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  backend:
    build: .
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: yarn start-backend
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}
