version: "3.4"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    command: node server.js
    container_name: mern-starter
    ports:
      - 4000:8080
    environment:
      NODE_ENV: production
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
